update public.teams
set name = case name
  when 'Algeria' then 'Argelia'
  when 'Argentina' then 'Argentina'
  when 'Australia' then 'Australia'
  when 'Austria' then 'Austria'
  when 'Belgium' then 'Bélgica'
  when 'Bolivia' then 'Bolivia'
  when 'Brazil' then 'Brasil'
  when 'Canada' then 'Canadá'
  when 'Cape Verde' then 'Cabo Verde'
  when 'Chile' then 'Chile'
  when 'China PR' then 'China'
  when 'Colombia' then 'Colombia'
  when 'Congo DR' then 'RD Congo'
  when 'Costa Rica' then 'Costa Rica'
  when 'Cote d''Ivoire' then 'Costa de Marfil'
  when 'Côte d’Ivoire' then 'Costa de Marfil'
  when 'Curacao' then 'Curazao'
  when 'Curaçao' then 'Curazao'
  when 'Ivory Coast' then 'Costa de Marfil'
  when 'Croatia' then 'Croacia'
  when 'Czech Republic' then 'República Checa'
  when 'Czechia' then 'República Checa'
  when 'Denmark' then 'Dinamarca'
  when 'Ecuador' then 'Ecuador'
  when 'Egypt' then 'Egipto'
  when 'England' then 'Inglaterra'
  when 'France' then 'Francia'
  when 'Germany' then 'Alemania'
  when 'Ghana' then 'Ghana'
  when 'Greece' then 'Grecia'
  when 'Haiti' then 'Haití'
  when 'Honduras' then 'Honduras'
  when 'Iran' then 'Irán'
  when 'Iraq' then 'Irak'
  when 'Italy' then 'Italia'
  when 'Japan' then 'Japón'
  when 'Jordan' then 'Jordania'
  when 'Korea Republic' then 'Corea del Sur'
  when 'South Korea' then 'Corea del Sur'
  when 'Mexico' then 'México'
  when 'Morocco' then 'Marruecos'
  when 'Netherlands' then 'Países Bajos'
  when 'New Zealand' then 'Nueva Zelanda'
  when 'Norway' then 'Noruega'
  when 'Panama' then 'Panamá'
  when 'Paraguay' then 'Paraguay'
  when 'Peru' then 'Perú'
  when 'Poland' then 'Polonia'
  when 'Portugal' then 'Portugal'
  when 'Qatar' then 'Catar'
  when 'Democratic Republic of Congo' then 'RD Congo'
  when 'Romania' then 'Rumania'
  when 'Saudi Arabia' then 'Arabia Saudita'
  when 'Scotland' then 'Escocia'
  when 'Senegal' then 'Senegal'
  when 'Serbia' then 'Serbia'
  when 'Slovakia' then 'Eslovaquia'
  when 'Slovenia' then 'Eslovenia'
  when 'South Africa' then 'Sudáfrica'
  when 'Spain' then 'España'
  when 'Sweden' then 'Suecia'
  when 'Switzerland' then 'Suiza'
  when 'Tunisia' then 'Túnez'
  when 'Turkey' then 'Turquía'
  when 'Ukraine' then 'Ucrania'
  when 'United States' then 'Estados Unidos'
  when 'Uruguay' then 'Uruguay'
  when 'USA' then 'Estados Unidos'
  when 'Uzbekistan' then 'Uzbekistán'
  when 'Venezuela' then 'Venezuela'
  when 'Wales' then 'Gales'
  else name
end,
updated_at = now()
where api_id like 'football-data:%';
